---
homeAssistant:
  token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI1YjY3NDhjZjE0ZTQ0Nzc4YTI5NjUyNGNlYTI0NjM2NSIsImlhdCI6MTY5NDQ1NjMzOSwiZXhwIjoyMDA5ODE2MzM5fQ._9x_ms5gS5jGWXgSNrxusd3hEOMNY-u1mdxV0ygpzOA"
  homeAssistantUrl: "http://ha.patres.dev"
  entityName: "input_select.work_status"
  availableOptionName: "Available"
  workingOptionName: "Working"
  meetingMicrophoneOptionName: "Meeting - microphone"
  meetingCameraOptionName: "Meeting - camera"
  turnOffOptionName: "Turn off"
window:
  pinned: true
  enablePreviousPosition: true
  positionX: 3273
  positionY: 467
workingTime:
  days:
  - "MONDAY"
  - "TUESDAY"
  - "WEDNESDAY"
  - "THURSDAY"
  - "FRIDAY"
  start: "09:00"
  end: "17:00"
currentMode: "AUTOMATION"
automationFrequencySeconds: 1.0
